services:
  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - stock-management-network-backend
    ports:
      - "5433:5432"
    restart: on-failure
    mem_limit: 1g
    cpus: 1.0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


  product-service:
    image: elifcelik49/stock-management-product-service:1.0.0
    container_name: product-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9788:9788"
    networks:
      - stock-management-network-backend
    restart: on-failure
    mem_limit: 1g
    cpus: 1.0
    environment:
      - "SPRING_PROFILES_ACTIVE=stage"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  spring-cloud-gateway:
    image: elifcelik49/stock-management-spring-cloud-gateway:1.0.0
    container_name: spring-cloud-gateway
    depends_on:
      - product-service
    networks:
      - stock-management-network-backend
    ports:
      - "8762:8762"
    restart: on-failure
    mem_limit: 1g
    cpus: 1.0
    environment:
      - "SPRING_PROFILES_ACTIVE=stage"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres-data:

networks:
  stock-management-network-backend:
    driver: bridge
